model_list:
  - model_name: ollama-codellama
    litellm_params:
      model: ollama/codellama:7b
      api_base: http://ollama:11434
    model_info: 
      version: 2                     # Ollama needs no key
      input_cost_per_token: 0.0000005
      output_cost_per_token: 0.0000015

general_settings:
  master_key: sk-ADMINKEY
  database_url: postgresql://postgres:postgres@postgres:5432/postgres
  store_model_in_db: true
  store_prompts_in_spend_logs: true

litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

callback_settings:
  otel:
    message_logging: True